apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: bri-job
  namespace: default

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-crud

subjects:
- kind: ServiceAccount
  name: bri-fire-analysis
  namespace: default
