apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: job-crud
  namespace: default

rules:
- apiGroups:
    - apps
    - batch
    - extensions

  resources:
    - jobs

  verbs:
    - "*"
  